// AWS
const AWS_ACCESS_KEY_ID = 'CHANGEME';
const AWS_SECRET_ACCESS_KEY = 'CHANGEME';


module.exports.AWS_ACCESS_KEY_ID = AWS_ACCESS_KEY_ID;
module.exports.AWS_SECRET_ACCESS_KEY = AWS_SECRET_ACCESS_KEY;
